### ISSUE TITLE
Page Shift when expanding description

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#12]
Sorry if a be picky, the page shifts when expanding the description in a sample, please see video:

https://user-images.githubusercontent.com/8781041/117784524-92c30100-b23b-11eb-8aaf-6da152091414.mp4

**Comment by pkbullock** [comment]
Its odd, other samples do not show this shift, so far just this one.

**Comment by v-aaronbode** [comment]
Hi @pkbullock, heads up that this not a bug but the intended functionality of the page (to maintain consistent padding between the last dropdown item and the footer). We will look at modifying this in a future iteration if general feedback is that it feels clunky.
