### ISSUE TITLE
Suggestion: Route for Contributors to improve their profile

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#16]
Just seen this profile and is missing metadata. Is there a suggested route that the authors can have a tidier profile. When its self-service or by form request?

![image](https://user-images.githubusercontent.com/8781041/117787817-b6d41180-b23e-11eb-902c-b56026f52d50.png)

**Comment by v-aaronbode** [comment]
The suggested route is to update their GitHub profile. Additionally, we have put logic in place to not display those empty fields, so all around this is now a much tidier and cleaner UI.
