### ISSUE TITLE
Sample broken

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#17]
The "All Microsoft 365 Groups and Teams" sample by Alison is very broken.

![image](https://user-images.githubusercontent.com/8781041/117788098-fb5fad00-b23e-11eb-957a-0e27967b4a9e.png)

**Comment by v-aaronbode** [comment]
This issue has been successfully resolved: https://adoption.microsoft.com/sample-solution-gallery/pnp-sp-dev-spfx-web-parts-react-groups-teams

Thanks!
