### ISSUE TITLE
Suggestion: View on GitHub - Open in new tab

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#18]
My preference would be to have the external links open in new tabs, if I were to check out multiple samples, I'm not a fan of being taken away from the site.

![image](https://user-images.githubusercontent.com/8781041/117789578-62ca2c80-b240-11eb-93aa-465a3a19146e.png)

**Comment by hugoabernier** [comment]
Hey @pkbullock, while I'm a big fan of opening in a new tab (you should see how many tabs I have opened now!), the Web Accessibility Guidelines advise against opening in a new tab (see https://www.w3.org/TR/WCAG20-TECHS/G200.html).

I think the reasoning is that if people want to open in a new tab, they can CTRL-click or right-click -- as long as the "View on GitHub" is presented as an actual hyperlink, and not using an `onclick` event to open the link.
