### ISSUE TITLE
Suggestion: Start with the newest samples

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#19]
Just a feeling of freshness if the **default view** were based on the latest samples. But this is just my feeling.... thoughts?

![image](https://user-images.githubusercontent.com/8781041/117789812-9f962380-b240-11eb-8e46-2141caf8a46c.png)

**Comment by v-aaronbode** [comment]
Thanks for the suggestion, @pkbullock! We have incorporated this into the gallery and it is live in production.
