### ISSUE TITLE
🐞 "view on GitHub more" does not work for script samples 😥

### ISSUE THREAD

**Issue by Adam-it** [pnp/m365-sample-gallery#40]
## 🐞 What's seems to be the problem?

It seems that when we click on "view on GitHub more" button for samples  coming from script samples repo 🤯 it does not redirect us properly and we end up in a `page-not-found`

## 👉 Example/ how to reproduce

It basically does not work for any sample coming from script-sample repo but we may take this one as example.
1. go to -> https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/bulk-undelete-from-recyclebin/ (related sample.json https://github.com/pnp/script-samples/tree/main/scripts/bulk-undelete-from-recyclebin/assets)
2. click on "view on GitHub more"
3. we should end up here (that is what is set in the sample.json) -> https://pnp.github.io/script-samples/bulk-undelete-from-recyclebin/README.html. but instead we end up here -> https://adoption.microsoft.com/en-us/page-not-found/ 😥

## 📽 Movie

https://user-images.githubusercontent.com/58668583/178246532-9726cdaa-99b9-4bcd-9001-9a9511987dea.mp4

## 🎯 How it should work?

When clicking on this button we should end up on a site that is set in the "url" property in the sample.json file. For the above example it should be 
![image](https://user-images.githubusercontent.com/58668583/178246692-856b7284-3cc8-4aa1-9321-931bc7ba8567.png)

## 🤔 My Ideas

I am no expert but I would double check the reason we have `null` in the url 😉
![image](https://user-images.githubusercontent.com/58668583/178246872-d995b7ec-d729-4bbf-bf63-dadd2d264d39.png)

let me know if you need any help with that 👍

**Comment by pkbullock** [comment]
@Adam-it - i've raised this internally, it may take a while to get resolved, re holidays etc. Will post back if i hear anything

**Comment by pkbullock** [comment]
Hi @Adam-it - we have discussed this and will be looked at soon, some key resources are on holiday so will be a few weeks before a fix is ready. Will update you when complete.

**Comment by Adam-it** [comment]
> Hi @Adam-it - we have discussed this and will be looked at soon, some key resources are on holiday so will be a few weeks before a fix is ready. Will update you when complete.

no rush. Glad that someone is looking into this 👍. @pkbullock you rock 🤩

**Comment by pkbullock** [comment]
This is now fixed! :-)

**Comment by Adam-it** [comment]
great news. lets close the issue then 👍
