### ISSUE TITLE
Suggestion: Tidier labelling for More Filters

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#9]
The labelling of metadata in the "More Filter" option, I feel needs to be friendlier/tidier. 

![image](https://user-images.githubusercontent.com/8781041/117782444-8b025d00-b239-11eb-954d-36c7b6f42c3b.png)

**Comment by v-aaronbode** [comment]
We have cleaned up the filter options and how they display so that it is a much cleaner UX. This issue has now been resolved and is live on the prod environment. Thanks, @pkbullock!
